### ISSUE TITLE
Slow feature extraction compared to bottom-up-attention

### ISSUE THREAD

**Issue by vinson2233** [microsoft/scene_graph_benchmark#8]
Hi, thanks for the great work and open-sourcing this project.

I'm excited to try VinVL since it promises faster computation time for the feature extraction part as written in the paper compared to bottom-up-attention
![image](https://user-images.githubusercontent.com/33550590/114685196-dbba8f00-9d3b-11eb-96dc-c90ded53954b.png)

I have created my own TSV file using `tsv_demo.py` and ran `tools/test_sg_net.py` to do feature extraction.
The sad thing is the feature extraction runs quite slowly.
Right now I'm using Pytorch 1.7, Debian 10, with 1 Nvidia T4.
The feature extraction process took **9 second / 4 images.**

I used bottom-up-attention from https://github.com/airsplay/py-bottom-up-attention and https://github.com/peteanderson80/bottom-up-attention while using OSCAR on the same dataset. these repo give much faster feature extraction time (the first repo need **2.7 seconds / 8 images,** while the original caffe bottom-up took less than 1 second for 1 image ) on a similar machine. This contradicts what written in your paper.

Here's some key config that I'm using while running the `tools/test_sg_net.py`

```yaml
TEST:
    IMS_PER_BATCH: 4
    IGNORE_BOX_REGRESSION: True
    SKIP_PERFORMANCE_EVAL: True
    SAVE_PREDICTIONS: True
    SAVE_RESULTS_TO_TSV: True
    TSV_SAVE_SUBSET: ['rect', 'class', 'conf', 'feature']
    GATHER_ON_CPU: True
    OUTPUT_FEATURE : True
```
I'm check my nvidia-smi and it showing my GPU is working.

Is anyone else have this issue also?
